Added Arcafile Support

diff --git a/arcabox b/arcabox
--- a/arcabox
+++ b/arcabox
@@ -7,11 +7,42 @@ RESET='\033[0m'
 BOLD='\033[1m'   
 UNDERLINE='\033[4m'
 trap ' ' SIGINT
-ARCAVERSION="1.5"
+ARCAVERSION="1.6-earlyalpha"
 if [ "$(id -u)" -ne 0 ]; then
     echo -e "${RED}${BOLD}=>${RESET}${BOLD} Please run as root${RESET}"
     exit 1
 fi
+check_file() {
+    local file="$1"
+
+    local found_name=false
+    local found_packages=false
+    local found_run=false
+
+    while IFS= read -r line; do
+        if [[ "$line" == name=* ]]; then
+            found_name=true
+        fi
+
+        if [[ "$line" == packages=* ]]; then
+            found_packages=true
+        fi
+
+    if [[ "$line" == scriptprogram=* ]]; then
+
+            found_run=true
+        fi
+
+    done < "$file"
+
+    # Exit immediately if any condition is not met
+    if ! $found_name || ! $found_packages || ! $found_run; then
+        echo -e "${BOLD}${RED}=> ${RESET}${BOLD}This Arcafile has been incorrectly scripted${BOLD}${RESET}"
+        exit 1
+    fi
+}
+
+
 fallback() {
     echo -e "${RED}${BOLD}=>${RESET}${BOLD}An error occurred. Cleaning up...${RESET}"
     umount -R "$ROOTPATH" || echo -e "${RED}${BOLD}=>${RESET}${BOLD}Failed to unmount $ROOTPATH.${RESET}"
@@ -48,7 +79,7 @@ if [ "$1" = "create" ]; then
     curl -o "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.zst --progress-bar || fallback
 
     echo -e "${BOLD}${GREEN}=>${RESET}${BOLD}Extracting the Tarball...${RESET}"
-    tar -xvf "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst -C "$TARGET_DIR" --numeric-owner || fallback
+    tar -xf "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst -C "$TARGET_DIR" --numeric-owner || fallback
 
     echo -e "${GREEN}=> ${BOLD}${RESET}${BOLD}Cleaning up...${RESET}"
     rm -rvf "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst "$TARGET_DIR"/pkglist.x86_64.txt
@@ -77,7 +108,7 @@ EOF
     "$CHROOTPROG" "$ROOTPATH" rm /setup.sh
     echo -e "${YELLOW}${BOLD}=> ${RESET}${BOLD}Setting up Pacman Mirrorlist${RESET}"
     if [ -f "/etc/pacman.d/mirrorlist" ]; then
-        echo -e "${BOLD}${GREEN}=> ${RESET}Found a pacman mirrorlist${BOLD}${RESET}"
+        echo -e "${BOLD}${GREEN}=> ${RESET}${BOLD}Found a pacman mirrorlist${BOLD}${RESET}"
         cp "/etc/pacman.d/mirrorlist" "$ROOTPATH/etc/pacman.d/mirrorlist"
     else
         echo "Server = https://geo.mirror.pkgbuild.com/\$repo/os/\$arch" >> "$ROOTPATH/etc/pacman.d/mirrorlist"
@@ -129,6 +160,8 @@ elif [ "$1" = "help" ]; then
     echo "clone <src> <dest>    -   Clone a container"
     echo
     echo "update        -   Update a container"
+    echo
+    echo "script        -   Run an Arcafile script"
     echo
     echo "Licensed with GNU GPL version 3"
 
@@ -221,7 +254,7 @@ elif [ "$1" = "restore" ]; then
     echo -e "${YELLOW}${BOLD}=> ${RESET}${BOLD}Listing Backups${RESET}"
     ls "$ROOTPATH/backups"
 
-    read -p "Enter the name of your backup (without .backup.tar.xz): " backupname
+    read -rp "Enter the name of your backup (without .backup.tar.xz): " backupname
 
     if [ -f "$ROOTPATH/backups/$backupname.backup.tar.xz" ]; then
         echo -e "${BOLD}${GREEN}=> ${RESET}${BOLD}Found $backupname ${RESET}"
@@ -292,6 +325,76 @@ elif [ "$1" = "version" ]; then
   |____| Licensed as GNU GPLv3
 EOF
 
+elif [ "$1" = "script" ]; then
+    if [ -z "$2" ]; then
+        if [ -f "Arcafile" ]; then
+            Arcafile="Arcafile"
+        else
+            echo -e "${BOLD}${RED}=>${RESET}${BOLD} Unable to find the Arcafile${RESET}"
+            exit 1
+        fi
+    else
+        Arcafile="$2"
+    fi
+    check_file "$Arcafile"
+    source "$Arcafile"
+        CONTAINER_NAME="$name"
+    TARGET_DIR="/usr/share/arcabox/arcafile/$name"
+
+    mkdir -p "$TARGET_DIR"
+    echo -e "${GREEN}${BOLD}=> ${RESET}${BOLD}Created ${RESET}${UNDERLINE}$TARGET_DIR${RESET}"
+
+    echo -e "${GREEN}${BOLD}=> ${RESET}${BOLD}Downloading the Tarball...${RESET}"
+    curl -o "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.zst --progress-bar || fallback
+
+    echo -e "${BOLD}${GREEN}=>${RESET}${BOLD}Extracting the Tarball...${RESET}"
+    tar -xf "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst -C "$TARGET_DIR" --numeric-owner || fallback
+
+    echo -e "${GREEN}=> ${BOLD}${RESET}${BOLD}Cleaning up...${RESET}"
+    rm -rvf "$TARGET_DIR"/archlinux-bootstrap-x86_64.tar.zst "$TARGET_DIR"/pkglist.x86_64.txt
+    ROOTPATH="$TARGET_DIR/root.x86_64" 
+    CHROOTPROG="$ROOTPATH/bin/arch-chroot"
+
+    echo -e "${BOLD}${YELLOW}=> ${RESET}${BOLD}Preparing for Setup...${RESET}"
+
+    mount --bind "$ROOTPATH" "$ROOTPATH" || fallback
+
+    echo -e "${BOLD}${YELLOW}=> ${RESET}${BOLD}Configuring the system${RESET}"
+
+    cat << EOF > "$ROOTPATH/setup.sh"
+    #!/bin/bash 
+    pacman-key --init
+    pacman-key --populate
+    exit
+EOF
+
+    chmod +x "$ROOTPATH/setup.sh"
+
+    # Run the setup.sh script inside the chroot
+    "$CHROOTPROG" "$ROOTPATH" bash /setup.sh || fallback
+
+    "$CHROOTPROG" "$ROOTPATH" rm /setup.sh
+    echo -e "${YELLOW}${BOLD}=> ${RESET}${BOLD}Setting up Pacman Mirrorlist${RESET}"
+    if [ -f "/etc/pacman.d/mirrorlist" ]; then
+        echo -e "${BOLD}${GREEN}=> ${RESET}Found a pacman mirrorlist${BOLD}${RESET}"
+        cp "/etc/pacman.d/mirrorlist" "$ROOTPATH/etc/pacman.d/mirrorlist"
+    else
+        echo "Server = https://geo.mirror.pkgbuild.com/\$repo/os/\$arch" >> "$ROOTPATH/etc/pacman.d/mirrorlist"
+    fi
+    echo -e "${BOLD}${GREEN}=> ${RESET}${BOLD}Updating the Package Repositories${RESET}"
+    "$CHROOTPROG" "$ROOTPATH" pacman --noconfirm -Sy || fallback
+    if [ ${#packages[@]} -gt 0 ]; then
+        for package in "${packages[@]}"; do
+            echo -e "${BOLD}${GREEN}=> ${RESET}${BOLD} Installing $package...${RESET}"
+            "$CHROOTPROG" "$ROOTPATH" pacman --noconfirm -S "$package" || fallback
+        done
+    fi
+    echo -e "${BOLD}${GREEN}=> ${RESET}${BOLD} Running the script function...${RESET}"
+    echo "#!/bin/bash" > "$ROOTPATH"/function.sh
+    echo "$scriptprogram" >> "$ROOTPATH"/function.sh
+    "$CHROOTPROG" "$ROOTPATH" "bash" "function.sh" || fallback
+    umount "$ROOTPATH"
+    rm -rf "$ROOTPATH"
 else
     echo -e "${RED}${BOLD}=>${RESET}${BOLD} Check 'arcabox help'${RESET}"
     exit 1
